{spawn, exec} = require 'child_process'
task 'livereload', "Start a livereload server", ->
  livereload = require('livereload')
  server = livereload.createServer({debug: true,applyJSLive: true})
  server.watch(__dirname + "/")

task 'develop', 'Continuously compiles files and reloads browser', ->
  invoke 'livereload'
  invoke 'watch'

task 'watch', 'continually build with --watch', ->
  src = spawn 'coffee', ['-cw', 'src']
  src.stdout.on 'data', (data) -> 
    console.log data.toString().trim()
    invoke 'test'
  
  spec = spawn 'coffee', ['-cw', 'spec']
  spec.stdout.on 'data', (data) -> 
    console.log data.toString().trim()
    invoke 'test'

task 'build', 'Compile coffeescript files', ->
  exec "coffee -c src", (err,stdout, stderr) ->
    console.log stdout
  
  exec "coffee -c spec", (err,stdout, stderr) ->
    console.log stdout
    
task 'test', 'Run the tests', ->
  console.log "running tests"
  file = "#{__dirname}/SpecRunner.html"
  exec "phantomjs lib/phantom-jasmine/lib/run_jasmine_test.coffee #{file}", (err,stdout, stderr) ->
      console.log  stdout  
