// Generated by CoffeeScript 1.3.3
(function() {

  describe("The ImageReplacer", function() {
    var sandbox;
    sandbox = $('<div id="sandbox"></div>');
    beforeEach(function() {
      return sandbox.appendTo("body");
    });
    afterEach(function() {
      return sandbox.empty();
    });
    describe("when on a large screen", function() {
      beforeEach(function() {
        return spyOn(ImageReplacer, "notMobile").andReturn(true);
      });
      it("replaces the given image with the large version", function() {
        sandbox.append("<img id='test' src='img1.png' data-large-image='img1-large.png'>");
        ImageReplacer.replace("#test");
        return expect($("#test").attr("src")).toEqual("img1-large.png");
      });
      return it("replaces all images with the large version", function() {
        sandbox.append("<img id='test' src='img1.png' data-large-image='img1-large.png'>");
        sandbox.append("<img id='test2' src='img2.png' data-large-image='img2-large.png'>");
        ImageReplacer.replaceAll();
        expect($("#test").attr("src")).toEqual("img1-large.png");
        return expect($("#test2").attr("src")).toEqual("img2-large.png");
      });
    });
    return describe("When on a small screen", function() {
      beforeEach(function() {
        return spyOn(ImageReplacer, "notMobile").andReturn(false);
      });
      return it("does not replace the image", function() {
        sandbox.append("<img id='test' src='img1.png' data-large-image='img1-large.png'>");
        ImageReplacer.replace("#test");
        return expect($("#test").attr("src")).toEqual("img1.png");
      });
    });
  });

}).call(this);
