// Generated by CoffeeScript 1.3.3
(function() {

  describe("The ImageReplacer", function() {
    it("replaces the given image with the large version", function() {
      $("body").append("<img id='test' src='img1.png' data-large-image='img1-large.png'>");
      ImageReplacer.replace("#test");
      return expect($("#test").attr("src")).toEqual("img1-large.png");
    });
    return it("replaces all images with the large version", function() {
      $("body").append("<img id='test' src='img1.png' data-large-image='img1-large.png'>");
      $("body").append("<img id='test2' src='img2.png' data-large-image='img2-large.png'>");
      ImageReplacer.replaceAll();
      expect($("#test").attr("src")).toEqual("img1-large.png");
      return expect($("#test2").attr("src")).toEqual("img2-large.png");
    });
  });

}).call(this);
