// Generated by CoffeeScript 1.6.2
(function() {
  this.ImageReplacer = {
    notMobile: function() {
      return $(window).width() > 480;
    },
    replaceAll: function() {
      var image, images, _i, _len, _results;

      images = $("img");
      _results = [];
      for (_i = 0, _len = images.length; _i < _len; _i++) {
        image = images[_i];
        _results.push(this.replace(image));
      }
      return _results;
    },
    replace: function(selector) {
      var image, large_image;

      if (this.notMobile()) {
        image = $(selector);
        large_image = image.attr("data-large-image");
        return image.attr("src", large_image);
      }
    }
  };

}).call(this);
